// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"

#include "student.hpp" // student implementations

//TESTS

TEST_CASE("ExerciseOne") //Named ExerciseOne, tagged with example
{
    CHECK(exerciseOne(7)=="James Bond");
    CHECK(exerciseOne(700)=="Dnob Semaj");
    CHECK(exerciseOne(117)=="John");
    CHECK(exerciseOne(616)=="Natasha Romanoff");
    CHECK(exerciseOne(17)=="Agent number 17 not found");
    CHECK(exerciseOne(89)=="Agent number 89 not found");
    CHECK(exerciseOne(32)=="Agent number 32 not found");
}

// Notes for teacher: 
// can use variables and libraries
// can use logic operators and loops
// you can run a specific test by using ./tests <TEST CASE NAME HERE>


